function m = mmap_mdh(filename)
%
% mmap_mdh
%
% 2009 by Thomas Witzel
% Massachusetts Institute of Technology
%
% This file contains proprietary information of Siemens Healthcare
% Solutions, DO NOT DISTRIBUTE !!!!
%
fid = fopen(filename,'r');

% first read the offset into the file
offset = fread(fid,1,'uint32');
disp(sprintf('offset = %d',offset));

% then figure out how many samples per readout there should be
fseek(fid,offset,'bof');
fseek(fid,28,'cof');
NSAMP = fread(fid,1,'uint16');
NChannels = fread(fid,1,'uint16');
disp(sprintf('nsamples in k-space line = %d',NSAMP));

% now figure out how many k-space lines there are 
fseek(fid,0,'eof');
endpos = ftell(fid);
dsize = endpos-offset;
% this calculation assumes that the scan was completed and there are
% ADCEND data for each channel (16 samples + header)
nlinesinfile = (dsize-NChannels*(16*8+128))/(NSAMP*8+128);
disp(sprintf('nlines in k-space data = %ld',nlinesinfile));
nrepeats = nlinesinfile;
fclose(fid);

m = memmapfile(filename,'Offset', offset,        ...  
     'Format', {                       ...
                'uint32',[1 1], 'ulDMALength';    ...
                'int32'  ,[1 1], 'lMeasUID'; ...
                'uint32' ,[1 1], 'ulScanCounter';  ...
                'uint32' ,[1 1], 'ulTimeStamp'; ...
                'uint32' ,[1 1], 'ulPMUTimeStamp'; ...
                'uint32' ,[1 2], 'aulEvalInfoMask'; ...
                'uint16' ,[1 1], 'ushSamplesInScan'; ... 
                'uint16' ,[1 1], 'ushUsedChannels'; ...            
                'uint16' ,[1 1], 'ushLine';         ...
                'uint16' ,[1 1], 'ushAcquisition';  ...                                                                        
                'uint16' ,[1 1], 'ushSlice';        ...                                                              
                'uint16' ,[1 1], 'ushPartition';    ...                                                                            
                'uint16' ,[1 1], 'ushEcho';         ...                                                                            
                'uint16' ,[1 1], 'ushPhase';        ...                                                                            
                'uint16' ,[1 1], 'ushRepetition';   ...                                                                             
                'uint16' ,[1 1], 'ushSet';          ...                                                                            
                'uint16' ,[1 1], 'ushSeg';          ...                                                                            
                'uint16' ,[1 1], 'ushIda';          ...                                                                            
                'uint16' ,[1 1], 'ushIdb';          ...                                                                            
                'uint16' ,[1 1], 'ushIdc';          ...                                                                            
                'uint16' ,[1 1], 'ushIdd';          ...                                                                            
                'uint16' ,[1 1], 'ushIde';          ...     
                'uint16' ,[1 1], 'ushPre';          ...                                                                           
                'uint16' ,[1 1], 'ushPost';         ...                                                                            
                'uint16' ,[1 1], 'ushKSpaceCentreColumn'; ...                                                                         
                'uint16' ,[1 1], 'ushCoilSelect'; ...              
               'single' ,[1 1], 'fReadOutOffcentre'; ...                                                                        
                'uint32' ,[1 1], 'ulTimeSinceLastRF';     ...                                                                     
                'uint16' ,[1 1], 'ushKSpaceCentreLineNo';  ...                                                                       
                'uint16' ,[1 1], 'ushKSpaceCentrePartitionNo'; ...                                                                    
                'uint16' ,[1 4], 'aushIceProgramPara';     ...                                                                    
                'uint16' ,[1 4], 'aushFreePara'; ...
                'single' ,[1 1], 'flSag'; ...
                'single' ,[1 1], 'flCor'; ...
                'single' ,[1 1], 'flTra'; ...
                'single' ,[1 4], 'aflQuaternion'; ...
                'uint16' ,[1 1], 'ushChannelId'; ...
                'uint16' ,[1 1], 'ushPTABPosNeg'; ...
                'single' ,[1 NSAMP*2], 'kdata'}, ...
     'Repeat',nrepeats);